Repository entando/entando-plugin-jpmail, pull requests merged in 2020-11, with the labels that each got.

#9 ENG-1478 Amend breadcrumbs
  src/main/java/com/agiletec/plugins/jpmail/apsadmin/global-messages_en.properties
  src/main/java/com/agiletec/plugins/jpmail/apsadmin/global-messages_it.properties
  src/main/webapp/WEB-INF/plugins/jpmail/apsadmin/jsp/mail/smtp-configuration.jsp
Labels: size/XS

#10 ENG-1478 Amend breadcrumbs
  src/main/webapp/WEB-INF/plugins/jpmail/apsadmin/jsp/mail/sender-entry.jsp
  src/main/webapp/WEB-INF/plugins/jpmail/apsadmin/jsp/mail/sender-list.jsp
  src/main/webapp/WEB-INF/plugins/jpmail/apsadmin/jsp/mail/sender-trash.jsp
  src/main/webapp/WEB-INF/plugins/jpmail/apsadmin/jsp/mail/smtp-configuration.jsp
Labels: size/S

#11 ENG-1512: Added extra param "csp.header.extraConfig"
  src/test/config/conf/systemParams.properties
Labels: approved, size/XS

#12 ENG-1512: Update BOM and snapshot version
  pom.xml
Labels: approved, size/XS
